language: python

python:
  - "2.7"

before_install:
  - export DJANGO_SETTINGS_MODULE=akvo.settings
  - export PYTHONPATH=$HOME/builds/akvo/akvo-rsr
  - echo '' > /var/log/akvo/akvo.log

install:
  - pip install -r scripts/deployment/pip/requirements/2_rsr.txt

script:
  - python manage.py test