language: python

python:
  - "2.7"

before_install:
  - export DJANGO_SETTINGS_MODULE=akvo.settings
  - export PYTHONPATH=$HOME/builds/akvo/akvo-rsr

install:
  - "pip install -r requirements.txt"

script:
  - python manage.py test